# Rust image
FROM rust:1.78-buster as builder

WORKDIR /usr/src/app

COPY . .

RUN cargo build --release

# Now copy it into our base image.
FROM gcr.io/distroless/cc-debian10

COPY --from=builder /usr/src/app/target/release/week1 /usr/local/bin/week1
CMD [ "week1" ]